import { readFileSync, writeFileSync } from 'node:fs';
// Input is public resource metadata only. Secret values must never enter this file.
const cfg = JSON.parse(readFileSync(process.argv[2], 'utf8').replace(/^\uFEFF/, ''));
if (cfg.account !== '578856792953' || cfg.region !== 'us-east-2') throw new Error('Unexpected deployment target');
const o = cfg.foundation;
const ref = Ref => ({ Ref });
const att = (id, key) => ({ 'Fn::GetAtt': [id, key] });
const sub = value => ({ 'Fn::Sub': value });
const tags = [{ Key: 'Project', Value: 'AIRS' }, { Key: 'Environment', Value: 'Production' }];
const Resources = {};
const add = (id, Type, Properties, rest = {}) => Resources[id] = { Type, Properties, ...rest };
for (const [id, name] of [['AppPassword', 'app-db-password'], ['MaintenancePassword', 'maintenance-db-password'], ['SessionSecret', 'session']]) add(id, 'AWS::SecretsManager::Secret', { Name: `airs-agent-prod/${name}`, GenerateSecretString: { PasswordLength: 48, ExcludePunctuation: true }, Tags: tags }, { DeletionPolicy: 'Retain', UpdateReplacePolicy: 'Retain' });
const roleTrust = { Version: '2012-10-17', Statement: [{ Effect: 'Allow', Principal: { Service: 'ecs-tasks.amazonaws.com' }, Action: 'sts:AssumeRole', Condition: { StringEquals: { 'aws:SourceAccount': cfg.account }, ArnLike: { 'aws:SourceArn': `arn:aws:ecs:${cfg.region}:${cfg.account}:*` } } }] };
const ecrArn = `arn:aws:ecr:${cfg.region}:${cfg.account}:repository/airs-agent`;
function executionRole(id, name, logSuffix, secrets) {
 add(id, 'AWS::IAM::Role', { RoleName: name, AssumeRolePolicyDocument: roleTrust, Policies: [{ PolicyName: 'ScopedExecution', PolicyDocument: { Version: '2012-10-17', Statement: [{ Effect: 'Allow', Action: 'ecr:GetAuthorizationToken', Resource: '*' }, { Effect: 'Allow', Action: ['ecr:BatchCheckLayerAvailability', 'ecr:GetDownloadUrlForLayer', 'ecr:BatchGetImage'], Resource: ecrArn }, { Effect: 'Allow', Action: ['logs:CreateLogStream', 'logs:PutLogEvents'], Resource: `arn:aws:logs:${cfg.region}:${cfg.account}:log-group:/ecs/airs-agent-prod${logSuffix}:*` }, { Effect: 'Allow', Action: 'secretsmanager:GetSecretValue', Resource: secrets }] } }], Tags: tags });
}
executionRole('WebExecutionRole', 'airs-agent-prod-web-execution-role', '', [ref('AppPassword'), ref('SessionSecret'), cfg.oidcSecretArn]);
executionRole('BootstrapExecutionRole', 'airs-agent-prod-bootstrap-execution-role', '-ops', [o.MasterSecretArn, ref('AppPassword'), ref('MaintenancePassword')]);
executionRole('MaintenanceExecutionRole', 'airs-agent-prod-maintenance-execution-role', '-maintenance', [ref('MaintenancePassword')]);
const url = user => `postgresql://${user}@${o.DatabaseEndpoint}:5432/airs_agent?sslmode=verify-full&sslrootcert=/app/certs/rds-us-east-2.pem`;
function task(id, family, image, role, name, environment, secrets, command, logSuffix, extra = {}) {
 const c = { Name: name, Image: image, Essential: true, User: 'node', Environment: Object.entries(environment).map(([Name, Value]) => ({ Name, Value })), Secrets: Object.entries(secrets).map(([Name, ValueFrom]) => ({ Name, ValueFrom })), LogConfiguration: { LogDriver: 'awslogs', Options: { 'awslogs-group': '/ecs/airs-agent-prod' + logSuffix, 'awslogs-region': cfg.region, 'awslogs-stream-prefix': name } }, ...extra };
 if (command) c.Command = command;
 add(id, 'AWS::ECS::TaskDefinition', { Family: family, Cpu: '512', Memory: '1024', NetworkMode: 'awsvpc', RequiresCompatibilities: ['FARGATE'], RuntimePlatform: { CpuArchitecture: 'ARM64', OperatingSystemFamily: 'LINUX' }, ExecutionRoleArn: att(role, 'Arn'), ContainerDefinitions: [c], Tags: tags });
}
task('WebTask', 'airs-agent-prod', cfg.webImage, 'WebExecutionRole', 'airs-agent', { NODE_ENV: 'production', PORT: '3000', HOST: '0.0.0.0', DB_DRIVER: 'postgres', AUTH_DRIVER: 'oidc', AIRS_PUBLIC_BASE_URL: 'https://app.airsagent.com', OIDC_ISSUER: `https://cognito-idp.${cfg.region}.amazonaws.com/${o.UserPool}`, OIDC_DOMAIN: `https://${o.UserPoolDomain}.auth.${cfg.region}.amazoncognito.com`, OIDC_CLIENT_ID: o.UserPoolClient, AIRS_APP_RELEASE: cfg.release, DATABASE_URL: url('airs_app') }, { PGPASSWORD: ref('AppPassword'), SESSION_SECRET: ref('SessionSecret'), OIDC_CLIENT_SECRET: cfg.oidcSecretArn }, null, '', { PortMappings: [{ ContainerPort: 3000, Protocol: 'tcp' }], HealthCheck: { Command: ['CMD-SHELL', `wget -qO- http://127.0.0.1:3000/api/public/health | grep -q '"status":"ok"' || exit 1`], Interval: 30, Timeout: 5, Retries: 3, StartPeriod: 30 } });
const bootstrap = `const {spawnSync}=require('node:child_process');const pg=require('pg');(async()=>{let p=spawnSync('node',['scripts/db-migrate.mjs'],{stdio:'inherit'});if(p.status!==0)process.exit(p.status||1);const c=new pg.Client({connectionString:process.env.DATABASE_URL});await c.connect();await c.query('BEGIN');for(const [role,key] of [['airs_app','APP_DB_PASSWORD'],['airs_maintenance','MAINT_DB_PASSWORD']]){const pw=process.env[key];if(!pw||pw.length<32)throw Error('Missing role credential');const r=await c.query('SELECT rolsuper,rolbypassrls,rolcreatedb,rolcreaterole,rolreplication FROM pg_roles WHERE rolname=$1',[role]);if(r.rows.length!==1||Object.values(r.rows[0]).some(Boolean))throw Error('Unsafe database role');await c.query('ALTER ROLE '+pg.escapeIdentifier(role)+' LOGIN PASSWORD '+pg.escapeLiteral(pw));}await c.query('COMMIT');await c.end();p=spawnSync('node',['scripts/db-migrate.mjs','--status'],{stdio:'inherit'});process.exit(p.status||0);})().catch(e=>{console.error('Bootstrap failed:',e.code||e.name);process.exit(1)});`;
task('BootstrapTask', 'airs-agent-prod-bootstrap', cfg.opsImage, 'BootstrapExecutionRole', 'bootstrap', { DATABASE_URL: url('postgres'), PGCONNECT_TIMEOUT: '15' }, { PGPASSWORD: `${o.MasterSecretArn}:password::`, APP_DB_PASSWORD: ref('AppPassword'), MAINT_DB_PASSWORD: ref('MaintenancePassword') }, ['node', '-e', bootstrap], '-ops');
task('MaintenanceTask', 'airs-agent-prod-maintenance', cfg.maintenanceImage ?? cfg.opsImage, 'MaintenanceExecutionRole', 'maintenance', { AIRS_MAINTENANCE_DATABASE_URL: url('airs_maintenance'), PGCONNECT_TIMEOUT: '15' }, { PGPASSWORD: ref('MaintenancePassword') }, ['node', 'scripts/expire-incident-state.mjs'], '-maintenance');
add('LoadBalancer', 'AWS::ElasticLoadBalancingV2::LoadBalancer', { Name: 'airs-agent-prod-alb', Scheme: 'internet-facing', Type: 'application', Subnets: [o.PublicA, o.PublicB], SecurityGroups: [o.AlbSecurityGroup], LoadBalancerAttributes: [{ Key: 'deletion_protection.enabled', Value: 'true' }], Tags: tags });
add('TargetGroup', 'AWS::ElasticLoadBalancingV2::TargetGroup', { Name: 'airs-agent-prod-web', VpcId: o.Vpc, Protocol: 'HTTP', Port: 3000, TargetType: 'ip', HealthCheckPath: '/api/public/health', HealthCheckIntervalSeconds: 30, HealthCheckTimeoutSeconds: 5, HealthyThresholdCount: 2, UnhealthyThresholdCount: 3, Matcher: { HttpCode: '200' }, Tags: tags });
add('HttpsListener', 'AWS::ElasticLoadBalancingV2::Listener', { LoadBalancerArn: ref('LoadBalancer'), Port: 443, Protocol: 'HTTPS', Certificates: [{ CertificateArn: cfg.certificateArn }], SslPolicy: 'ELBSecurityPolicy-TLS13-1-2-2021-06', DefaultActions: [{ Type: 'forward', TargetGroupArn: ref('TargetGroup') }] });
add('HttpListener', 'AWS::ElasticLoadBalancingV2::Listener', { LoadBalancerArn: ref('LoadBalancer'), Port: 80, Protocol: 'HTTP', DefaultActions: [{ Type: 'redirect', RedirectConfig: { Protocol: 'HTTPS', Port: '443', StatusCode: 'HTTP_301' } }] });
const network = { AwsvpcConfiguration: { AssignPublicIp: 'DISABLED', Subnets: [o.PrivateA, o.PrivateB], SecurityGroups: [o.EcsSecurityGroup] } };
add('Service', 'AWS::ECS::Service', { ServiceName: 'airs-agent-prod', Cluster: o.Cluster, LaunchType: 'FARGATE', PlatformVersion: '1.4.0', DesiredCount: ref('DesiredCount'), TaskDefinition: ref('WebTask'), NetworkConfiguration: network, LoadBalancers: [{ ContainerName: 'airs-agent', ContainerPort: 3000, TargetGroupArn: ref('TargetGroup') }], HealthCheckGracePeriodSeconds: 90, DeploymentConfiguration: { MinimumHealthyPercent: 100, MaximumPercent: 200, DeploymentCircuitBreaker: { Enable: true, Rollback: true } }, EnableECSManagedTags: true, PropagateTags: 'SERVICE', Tags: tags }, { DependsOn: 'HttpsListener' });
add('SchedulerRole', 'AWS::IAM::Role', { RoleName: 'airs-agent-prod-scheduler-role', AssumeRolePolicyDocument: { Version: '2012-10-17', Statement: [{ Effect: 'Allow', Principal: { Service: 'events.amazonaws.com' }, Action: 'sts:AssumeRole', Condition: { StringEquals: { 'aws:SourceAccount': cfg.account }, ArnLike: { 'aws:SourceArn': `arn:aws:events:${cfg.region}:${cfg.account}:rule/airs-agent-prod-expiration` } } }] }, Policies: [{ PolicyName: 'RunMaintenanceOnly', PolicyDocument: { Version: '2012-10-17', Statement: [{ Effect: 'Allow', Action: 'ecs:RunTask', Resource: ref('MaintenanceTask'), Condition: { ArnEquals: { 'ecs:cluster': `arn:aws:ecs:${cfg.region}:${cfg.account}:cluster/${o.Cluster}` } } }, { Effect: 'Allow', Action: 'iam:PassRole', Resource: att('MaintenanceExecutionRole', 'Arn'), Condition: { StringEquals: { 'iam:PassedToService': 'ecs-tasks.amazonaws.com' } } }] } }], Tags: tags });
add('ExpirationSchedule', 'AWS::Events::Rule', { Name: 'airs-agent-prod-expiration', ScheduleExpression: 'rate(5 minutes)', State: ref('ScheduleState'), Targets: [{ Id: 'maintenance', Arn: `arn:aws:ecs:${cfg.region}:${cfg.account}:cluster/${o.Cluster}`, RoleArn: att('SchedulerRole', 'Arn'), EcsParameters: { TaskDefinitionArn: ref('MaintenanceTask'), TaskCount: 1, LaunchType: 'FARGATE', PlatformVersion: '1.4.0', NetworkConfiguration: { AwsVpcConfiguration: network.AwsvpcConfiguration } }, RetryPolicy: { MaximumRetryAttempts: 2, MaximumEventAgeInSeconds: 240 } }] });
for (const [id, metric, threshold] of [['HighCpu', 'CPUUtilization', 80], ['HighMemory', 'MemoryUtilization', 85]]) add(id, 'AWS::CloudWatch::Alarm', { AlarmName: `airs-agent-prod-${metric}`, Namespace: 'AWS/ECS', MetricName: metric, Dimensions: [{ Name: 'ClusterName', Value: o.Cluster }, { Name: 'ServiceName', Value: 'airs-agent-prod' }], Statistic: 'Average', Period: 60, EvaluationPeriods: 5, Threshold: threshold, ComparisonOperator: 'GreaterThanThreshold', TreatMissingData: 'notBreaching' });
add('UnhealthyTargets', 'AWS::CloudWatch::Alarm', { AlarmName: 'airs-agent-prod-unhealthy-targets', Namespace: 'AWS/ApplicationELB', MetricName: 'UnHealthyHostCount', Dimensions: [{ Name: 'LoadBalancer', Value: att('LoadBalancer', 'LoadBalancerFullName') }, { Name: 'TargetGroup', Value: att('TargetGroup', 'TargetGroupFullName') }], Statistic: 'Maximum', Period: 60, EvaluationPeriods: 3, Threshold: 0, ComparisonOperator: 'GreaterThanThreshold', TreatMissingData: 'notBreaching' });
add('AlertsTopic', 'AWS::SNS::Topic', { TopicName: 'airs-agent-prod-alerts', Tags: tags });
add('AlertsEmail', 'AWS::SNS::Subscription', { TopicArn: ref('AlertsTopic'), Protocol: 'email', Endpoint: 'admin@airsagent.com' });
add('DatabaseLowStorage', 'AWS::CloudWatch::Alarm', { AlarmName: 'airs-agent-prod-database-low-storage', Namespace: 'AWS/RDS', MetricName: 'FreeStorageSpace', Dimensions: [{Name:'DBInstanceIdentifier',Value:'airs-agent-prod-db'}], Statistic:'Minimum', Period:300, EvaluationPeriods:2, Threshold:5368709120, ComparisonOperator:'LessThanThreshold', TreatMissingData:'missing' });
add('MaintenanceFailureMetric', 'AWS::Logs::MetricFilter', { LogGroupName:'/ecs/airs-agent-prod-maintenance', FilterPattern:'{ $.event = "maintenance.expiration_failed" }', MetricTransformations:[{MetricNamespace:'AIRS/Production',MetricName:'MaintenanceFailures',MetricValue:'1',DefaultValue:0}] });
add('MaintenanceFailures', 'AWS::CloudWatch::Alarm', {AlarmName:'airs-agent-prod-maintenance-failures', Namespace:'AIRS/Production',MetricName:'MaintenanceFailures',Statistic:'Sum',Period:300,EvaluationPeriods:1,Threshold:0,ComparisonOperator:'GreaterThanThreshold',TreatMissingData:'notBreaching'});
for (const resource of Object.values(Resources)) if(resource.Type==='AWS::CloudWatch::Alarm'){resource.Properties.AlarmActions=[ref('AlertsTopic')];resource.Properties.OKActions=[ref('AlertsTopic')];}
const Outputs = { LoadBalancerDns: { Value: att('LoadBalancer', 'DNSName') }, LoadBalancerArn: { Value: ref('LoadBalancer') }, TargetGroupArn: { Value: ref('TargetGroup') } };
for (const id of ['BootstrapTask', 'MaintenanceTask', 'WebTask', 'AppPassword', 'MaintenancePassword', 'SessionSecret']) Outputs[id] = { Value: ref(id) };
writeFileSync(new URL('./runtime.cloudformation.json', import.meta.url), JSON.stringify({ AWSTemplateFormatVersion: '2010-09-09', Description: 'AIRS Ohio runtime; start desired count at zero until database bootstrap passes.', Parameters: { DesiredCount: { Type: 'Number', Default: 0, AllowedValues: [0, 1, 2] }, ScheduleState: { Type: 'String', Default: 'DISABLED', AllowedValues: ['ENABLED', 'DISABLED'] } }, Resources, Outputs }, null, 2) + '\n');
