// Portable RBAC model. Mirrors db/migrations/0002_roles_seed.sql.
// Pure TypeScript: no platform SDKs, usable by any backend runtime.

export const ROLE_KEYS = [
  "agency_admin",
  "airspace_supervisor",
  "rpic",
  "visual_observer",
  "dispatcher",
  "incident_commander",
  "intel_analyst",
  "partner_agency_user",
  "system_auditor",
] as const;
export type RoleKey = (typeof ROLE_KEYS)[number];

export const PERMISSION_KEYS = [
  "org.manage",
  "user.manage",
  "incident.create",
  "incident.read",
  "incident.update",
  "incident.close",
  "incident.share",
  "incident.revoke_share",
  "incident.activate",
  "incident.pause",
  "incident.resume",
  "incident.archive",
  "incident.invite_partner",
  "incident.approve_partner",
  "incident.restrict_partner",
  "incident.remove_partner",
  "incident.view_participants",
  "airspace.read",
  "airspace.propose",
  "airspace.approve",
  "aircraft.manage",
  "audit.read",
  "retention.manage",
  "resource.create",
  "resource.read",
  "resource.update",
  "resource.retire",
  "resource.restore",
  "resource.set_status",
  "resource.share",
  "resource.revoke_share",
  "resource.assign_incident",
  "resource.release_incident",
  "personnel.readiness_manage",
  "personnel.schedule_manage",
  "qualification.manage",
  "qualification.verify",
  "qualification.revoke",
] as const;
export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const ROLE_LABELS: Record<RoleKey, string> = {
  agency_admin: "Agency Administrator",
  airspace_supervisor: "Airspace Supervisor",
  rpic: "Remote Pilot in Command",
  visual_observer: "Visual Observer",
  dispatcher: "Dispatcher / RTCC Operator",
  incident_commander: "Incident Commander",
  intel_analyst: "Intelligence Analyst",
  partner_agency_user: "Partner-Agency User",
  system_auditor: "System Auditor",
};

export const ROLE_PERMISSIONS: Record<RoleKey, readonly PermissionKey[]> = {
  agency_admin: [
    "org.manage",
    "user.manage",
    "incident.read",
    "incident.archive",
    "incident.view_participants",
    "airspace.read",
    "aircraft.manage",
    "retention.manage",
    "audit.read",
    "resource.create",
    "resource.read",
    "resource.update",
    "resource.retire",
    "resource.restore",
    "resource.set_status",
    "resource.share",
    "resource.revoke_share",
    "personnel.readiness_manage",
    "personnel.schedule_manage",
    "qualification.manage",
    "qualification.verify",
    "qualification.revoke",
  ],
  airspace_supervisor: [
    "incident.read",
    "incident.view_participants",
    "airspace.read",
    "airspace.approve",
    "airspace.propose",
    "aircraft.manage",
    "resource.read",
    "resource.update",
    "resource.set_status",
    "resource.share",
    "resource.revoke_share",
    "resource.assign_incident",
    "resource.release_incident",
    "personnel.readiness_manage",
    "personnel.schedule_manage",
    "qualification.verify",
  ],
  rpic: [
    "incident.read",
    "airspace.read",
    "airspace.propose",
    "resource.read",
    "resource.set_status",
  ],
  visual_observer: ["incident.read", "airspace.read", "resource.read"],
  dispatcher: [
    "incident.create",
    "incident.read",
    "incident.update",
    "incident.activate",
    "incident.pause",
    "incident.resume",
    "incident.view_participants",
    "airspace.read",
    "resource.read",
    "resource.set_status",
    "resource.assign_incident",
    "resource.release_incident",
    "personnel.readiness_manage",
    "personnel.schedule_manage",
  ],
  incident_commander: [
    "incident.create",
    "incident.read",
    "incident.update",
    "incident.close",
    "incident.share",
    "incident.revoke_share",
    "incident.activate",
    "incident.pause",
    "incident.resume",
    "incident.archive",
    "incident.invite_partner",
    "incident.approve_partner",
    "incident.restrict_partner",
    "incident.remove_partner",
    "incident.view_participants",
    "airspace.read",
    "airspace.approve",
    "resource.read",
    "resource.set_status",
    "resource.share",
    "resource.revoke_share",
    "resource.assign_incident",
    "resource.release_incident",
  ],
  intel_analyst: ["incident.read", "incident.view_participants", "airspace.read", "resource.read"],
  partner_agency_user: [
    "incident.read",
    "incident.view_participants",
    "airspace.read",
    "resource.read",
  ],
  system_auditor: ["audit.read"],
};
