/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiMaintenanceExpireIncidentsRouteImport } from './routes/api/maintenance/expire-incidents'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncidentsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceExpireIncidentsRoute =
  ApiMaintenanceExpireIncidentsRouteImport.update({
    id: '/api/maintenance/expire-incidents',
    path: '/api/maintenance/expire-incidents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/api/maintenance/expire-incidents': typeof ApiMaintenanceExpireIncidentsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/resources': typeof ResourcesRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/incidents': typeof IncidentsIndexRoute
  '/api/maintenance/expire-incidents': typeof ApiMaintenanceExpireIncidentsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/api/maintenance/expire-incidents': typeof ApiMaintenanceExpireIncidentsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/incidents'
    | '/resources'
    | '/incidents/$incidentId'
    | '/invite/$token'
    | '/incidents/'
    | '/api/maintenance/expire-incidents'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/console'
    | '/resources'
    | '/incidents/$incidentId'
    | '/invite/$token'
    | '/incidents'
    | '/api/maintenance/expire-incidents'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/console'
    | '/incidents'
    | '/resources'
    | '/incidents/$incidentId'
    | '/invite/$token'
    | '/incidents/'
    | '/api/maintenance/expire-incidents'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiMaintenanceExpireIncidentsRoute: typeof ApiMaintenanceExpireIncidentsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance/expire-incidents': {
      id: '/api/maintenance/expire-incidents'
      path: '/api/maintenance/expire-incidents'
      fullPath: '/api/maintenance/expire-incidents'
      preLoaderRoute: typeof ApiMaintenanceExpireIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiMaintenanceExpireIncidentsRoute: ApiMaintenanceExpireIncidentsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
